### ISSUE TITLE
OpenSSL::SSL::SSLError when sending SMS

### ISSUE THREAD

**Issue by dball** [philm/twilio#7]
I get this when I tried to send my first SMS:

OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
    from /Users/dball/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/net/http.rb:586:in `connect'
    from /Users/dball/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/net/http.rb:586:in`connect'
    from /Users/dball/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/net/http.rb:553:in `do_start'
    from /Users/dball/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/net/http.rb:542:in`start'
    from /Users/dball/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/net/http.rb:1035:in `request_without_newrelic_trace'
    from /Users/dball/.rvm/gems/ree-1.8.7-2011.03@decisiv/gems/newrelic_rpm-2.14.1/lib/new_relic/agent/instrumentation/net.rb:16:in`request'
    from /Users/dball/.rvm/gems/ree-1.8.7-2011.03@decisiv/gems/newrelic_rpm-2.14.1/lib/new_relic/agent/method_tracer.rb:193:in `trace_execution_scoped'
    from /Users/dball/.rvm/gems/ree-1.8.7-2011.03@decisiv/gems/newrelic_rpm-2.14.1/lib/new_relic/agent/instrumentation/net.rb:15:in`request'
    from /Users/dball/.rvm/gems/ree-1.8.7-2011.03@decisiv/gems/httparty-0.7.7/lib/httparty/request.rb:69:in `perform'
    from /Users/dball/.rvm/gems/ree-1.8.7-2011.03@decisiv/gems/httparty-0.7.7/lib/httparty.rb:390:in`perform_request'
    from /Users/dball/.rvm/gems/ree-1.8.7-2011.03@decisiv/gems/httparty-0.7.7/lib/httparty.rb:358:in `post'
    from /Users/dball/.rvm/gems/ree-1.8.7-2011.03@decisiv/gems/twilio-3.0.0/lib/twilio/sms.rb:10:in`message'

I presume this is because Twilio is using a self-signed cert or one with a hostname mismatch, but being new to httparty, I'm not sure the best way to solve this. Perhaps, if this is the expected state of affairs, it would be appropriate for the twilio gem to embed the cert it expects?

**Comment by dball** [comment]
FWIW, I solved this by copying the cacert.pem from active_merchant into my Rails app and configuring it in an initializer.

**Comment by jwigal** [comment]
This worked for me as well. I grabbed the CA file from here:

http://curl.haxx.se/ca/cacert.pem

and put this into an initializer:

```
Twilio.default_options[:ssl_ca_file] = File.join(Rails.root,"config/cacert.pem")
Twilio.default_options[:ssl_ca_path] = File.join(Rails.root,"config")
```
